name: GitHub Actions Demo
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    steps:
      - run: echo "github.ref= ${{ github..ref }}"
      - run: echo "github.head_ref= ${{ github.head_ref }}"
      - run: echo "github.base_ref= ${{ github.base_ref }}"
      - run: echo "pr_name= $(echo ${{ steps.extract_branch.outputs.branch }})"
